### ISSUE TITLE
Somehow removes services inside the deployment after applying the tag

### ISSUE THREAD

**Issue by mark-hartmann** [mark-hartmann/update-deployment-action#9]

**Comment by mark-hartmann** [comment]
After some trial and error I found that this problem occurs when a service is defined at the end of the document stream. With deployments this does not happen, at least I could not replicate it.

``` yaml
apiVersion: v1
kind: Deployment
<other keys>
---
apiVersion: v1
kind: Deployment
<other keys>
```
&
``` yaml
apiVersion: v1
kind: Service
<other keys>
---
apiVersion: v1
kind: Deployment
<other keys>
```

are perfectly fine. A service at the end of the file gets lost, a service in the middle of two deployments results in the following:

``` yaml
apiVersion: v1
kind: Deployment
<other keys>
---
---
apiVersion: v1
kind: Service
<other keys>
---
apiVersion: v1
kind: Deployment
<other keys>
```
